# fly.toml app configuration file generated for icy-brook-7624 on 2023-06-11T21:58:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "icy-brook-7624"
primary_region = "iad"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
